### ISSUE TITLE
If I disable the popup over then how can I overwrite the selection?

### ISSUE THREAD

**Issue by dipakvarma159** [amrit260/react-selection-highlighter#2]
I want to overwrite the selection everytime means I want to select text only single time. How can I do that? If I get the latest selection text then I can overwrite but How can I get latest selection?

**Comment by amrit787** [comment]
You have the option to utilize hooks for retrieving selections, and it's also possible to adjust classnames and you can add your own keys to selection object  as needed.

`const { selections, setSelections, updateSelection, removeSelections } = useSelections()`

**Comment by dipakvarma159** [comment]
Can I get the latest selected object after selecting the text through these hooks? I tried with selections but it's returning all the selected objects but, in my case, I need to select only one text any time. if I try to select any text again then it should be replaced with the latest selection. Please share the code snippet it will be helpful to me.

**Comment by amrit787** [comment]
At present, there isn't a direct method to achieve the functionality  you're looking for. However, I plan to include this feature in our future updates. Thank you for your patience and suggestion.

Since you need only one selection, one workaround might me that you can clear all selections and add last selection to selections state every time the "selections" state changes (I'm not sure about this).

**Comment by dipakvarma159** [comment]
Thanks for the quick response. I am not able to get the last selection that's the only issue. selections state shows me all items. I am unable to identify my last selection from selections state array. if I get the latest selection as a last item in selections state. but I think the array is sorting in ascending order. so unable to find it.

**Comment by amrit787** [comment]
Thank you for bringing this to our attention. I understand the importance of this feature and will be sure to include an onSelection event in our next update. Your feedback is invaluable, and I appreciate your initiative in opening this issue.

**Comment by amrit787** [comment]
You can now use onSelect() method
